# Generated by Django 2.2.2 on 2021-05-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
