# Generated by Django 2.2.2 on 2021-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
