# Generated by Django 2.2.2 on 2021-05-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_auto_20210511_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
