# Generated by Django 2.2.2 on 2021-05-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_auto_20210502_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='company',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='lot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='plate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
