# Generated by Django 2.2.2 on 2021-05-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0003_auto_20210511_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='parking_id',
            new_name='id',
        ),
    ]
